apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: webapp-ns
spec:
  selector:
    lbtype: external
    app: nginx
  type: NodePort
  ports:
  - name: nginx
    port: 80
    targetPort: 80
    nodePort: 31600