apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        lbtype: external
        app: nginx
    spec:
      containers:
        - name: nginx
          image: us-ashburn-1.ocir.io/<DOCKER_OBJECT_STORAGE_NAMESPACE>/kubernetes-nginx:latest
          ports:
            - containerPort: 80
              name: "80-port"
      imagePullSecrets:
      - name: registry-secret